namespace ASTGen;

public static class AST
{
    public static string DefineType(string baseName, string className, string fieldList)
    {
        var fields = fieldList.Trim().Split(',');

        var constructorInitializers = fields.Select(field =>
        {
            field = field.Trim();
            var name = field.Split(' ')[1];
            var startsWithAt = name.StartsWith('@');
            var capitalizedName = string.Empty;

            if (startsWithAt)
                capitalizedName = char.ToUpper(name[1]) + name[2..];
            else
                capitalizedName = char.ToUpper(name[0]) + name[1..];

            return $"{capitalizedName} = {name};";
        });

        var fieldDefinitions = fields.Select(field =>
        {
            field = field.Trim();
            var type = field.Split(' ')[0];
            var name = field.Split(' ')[1];
            var firstLetter = name.StartsWith('@') ? 1 : 0;
            var startsWithAt = name.StartsWith('@');
            var capitalizedName = string.Empty;
            if (startsWithAt)
                capitalizedName = char.ToUpper(name[1]) + name[2..];
            else
                capitalizedName = char.ToUpper(name[0]) + name[1..];

            return $"public {type} {capitalizedName} {{ get; private set; }}";
        });

        return @$"public class {className} : {baseName}
{{
    {string.Join('\n', fieldDefinitions)}

    public {className}({string.Join(",", fields)})
    {{
        {string.Join('\n', constructorInitializers)}
    }}

    public override T Accept<T>(IVisitor<T> visitor) 
    {{
        return visitor.Visit{className}{baseName}(this);
    }}
}}";
    }

    public static void DefineAST(string outputDir, string baseName, IEnumerable<string> types)
    {
        var outputFilename = Path.Combine(outputDir, $"{baseName}.cs");
        var definitions = types.Select(type =>
        {
            type = type.Trim();
            var className = type.Split(':')[0].Trim();
            var fields = type.Split(':')[1].Trim();

            return DefineType(baseName, className, fields);
        });
        var content = @$"// File autogenerated by ASTGen on {DateTime.Now:g}

using Lox.Tokens;
    
namespace Lox.Generated;

public abstract class {baseName}
{{
    {string.Join('\n', definitions)}
    
    public abstract T Accept<T>(IVisitor<T> visitor);

    {string.Join('\n', DefineVisitors(baseName, types))}
}}
";

        File.WriteAllText(outputFilename, content);
    }

    public static string DefineVisitors(string baseName, IEnumerable<string> types)
    {
        var typeVisitors = types.Select(type =>
        {
            var typeName = type.Split(':')[0].Trim();
            return @$"T Visit{typeName}{baseName}({typeName} {baseName.ToLower()});";
        });

        return @$"public interface IVisitor<T> {{
        {string.Join('\n', typeVisitors)}
}}";
    }
}